name: CI

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    actions: read
    contents: read
    deployments: write
    packages: write
    attestations: write
    id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: "pnpm: setup"
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            # This enables task distribution via Nx Cloud
            # Run this command as early as possible, before dependencies are installed
            # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
          #            - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

            # Cache node_modules
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "pnpm"

            - uses: actions/setup-go@v5
              with:
                go-version: '^1.22.0'
                cache-dependency-path: api/go.sum

            - name: "pnpm: install"
              run: pnpm install

            - name: "railway: install"
              run: pnpm i -g @railway/cli

            - uses: nrwl/nx-set-shas@v4
              with:
                main-branch-name: "master"

            # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
            # - run: npx nx-cloud record -- echo Hello World
            # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
          # --no-agents disables remote task execution
            - run: npx nx affected -t lint test build

            - name: "Cloudflare: publish"
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
                projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
                directory: dist/client/browser
                # Optional: Enable this if you want to have GitHub Deployments triggered
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                # Optional: Switch what branch you are publishing to.
                # By default this will be the branch which triggered this workflow
                branch: main
                # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
                wranglerVersion: '3'

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: "Docker: extract metadata (tags, labels)"
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  # set latest tag for default branch
                  type=raw,value=latest,enable={{is_default_branch}}

            - name: "Docker: build and push"
              id: push
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                context: .
                file: api/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            - name: "Docker: generate artifact attestation"
              uses: actions/attest-build-provenance@v1
              with:
                subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true

            - name: "railway: re-deploy"
              run: railway redeploy --service 'Habit Api' --yes
              env:
                RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}